---
- name: Add Wazuh repository
  yum_repository:
    name: wazuh
    description: Wazuh repository
    baseurl: https://packages.wazuh.com/4.x/yum/
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    gpgcheck: yes

- name: Install Wazuh manager
  yum:
    name: wazuh-manager
    state: present

- name: Configure Wazuh manager
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    backup: yes
  notify: restart wazuh-manager

- name: Install custom rules
  copy:
    src: "{{ item }}"
    dest: /var/ossec/etc/rules/
  with_fileglob:
    - "../../../wazuh/rules/*.xml"
  notify: restart wazuh-manager

- name: Start and enable Wazuh manager
  systemd:
    name: wazuh-manager
    state: started
    enabled: yes

- name: Configure API
  template:
    src: api.yaml.j2
    dest: /var/ossec/api/configuration/api.yaml
  notify: restart wazuh-manager