---
- name: Automated Threat Response
  hosts: localhost
  gather_facts: false
  vars:
    threat_level: "{{ threat_level | default('medium') }}"
  
  tasks:
    - name: Block suspicious IP
      uri:
        url: "https://192.168.198.133:55000/security/user/authenticate"
        method: POST
        body_format: json
        body:
          user: "{{ wazuh_api_user }}"
          password: "{{ wazuh_api_password }}"
        retries: 3
        delay: 10
      register: wazuh_auth

    - name: Add IP to blocklist
      uri:
        url: "https://192.168.198.133:55000/lists/files/blocked-ips"
        method: POST
        headers:
          Authorization: "Bearer {{ wazuh_auth.json.data.token }}"
        body: "{{ suspicious_ip }}"
        retries: 3
        delay: 5
      when: threat_level in ['high', 'critical']

    - name: Rotate compromised credentials
      uri:
        url: "https://192.168.198.133:8200/v1/sys/leases/revoke-prefix/database/creds"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          lease_id: "{{ compromised_lease_id }}"
        retries: 3
        delay: 10
      when: threat_level == 'critical'