---
- name: Security Platform Infrastructure Validation
  hosts: security_platform
  gather_facts: yes
  tasks:
    - name: Check disk space (20GB+ required)
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space
      failed_when: disk_space.stdout|regex_replace('G','') | int < 20

    - name: Check memory allocation (6GB+ required)
      shell: free -m | awk 'NR==2{printf "%.0f", $2/1024}'
      register: memory_total
      failed_when: memory_total.stdout | int < 6

    - name: Test internet connectivity
      uri:
        url: https://releases.hashicorp.com
        method: HEAD
        timeout: 10
      retries: 3
      delay: 5

    - name: Verify DNS resolution
      shell: nslookup packages.wazuh.com
      register: dns_check
      failed_when: dns_check.rc != 0

    - name: Check SSH connectivity to protected infrastructure
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 10
      loop:
        - "192.168.198.131"  # app-server
        - "192.168.198.132"  # file-server
        - "192.168.198.134"  # elk-platform

    - name: Validate security platform IP assignment
      debug:
        msg: "Security platform configured for {{ ansible_host }}"
      failed_when: ansible_host != "192.168.198.133"